const ADD = 'ADD';
const SUB = 'SUB';
const ADD_NUMBER = 'NUM';
const ADD2 = 'ADD2';
const ADD_BOARD = 'ADD_BOARD';
const ADD_COLUMN = 'ADD_COLUMN';
const ADD_TASK = 'ADD_TASK';
const MOVE_COLUMN = 'MOVE_COLUMN';
const MOVE_TASK = 'MOVE_TASK';
const SET_DRAGGED_ITEM = 'SET_DRAGGED_ITEM';
const DELETE_TASK = 'DELETE_TASK';
const DELETE_COLUMN = 'DELETE_COLUMN';
const DELETE_BOARD = 'DELETE_BOARD';
const CHANGE_TEXT = 'CHANGE_TEXT';
const SET_AUTH_TRUE = 'SET_AUTH_TRUE';
const SET_AUTH_FALSE = 'SET_AUTH_FALSE';

export {
  ADD,
  SUB,
  ADD_NUMBER,
  ADD2,
  ADD_BOARD,
  ADD_COLUMN,
  ADD_TASK,
  MOVE_COLUMN,
  MOVE_TASK,
  SET_DRAGGED_ITEM,
  DELETE_TASK,
  DELETE_COLUMN,
  DELETE_BOARD,
  CHANGE_TEXT,
  SET_AUTH_TRUE,
  SET_AUTH_FALSE,
};
